# CLASSIFIERS TO CLASSIFY CATS, COWS, DOGS.

In [1]:
from sklearn.preprocessing import LabelEncoder
from PIL import Image
import numpy as np
import os

In [2]:
path=os.getcwd()
data_path1=path+'/Dataset'
img_list1=os.listdir(data_path1)

In [3]:
def color_feat(img):
    (r,g,b)=img.split()
    feat=[np.mean(r),np.mean(g),np.mean(b),np.std(r),np.std(g),np.std(b)]
    return feat

In [4]:
data=[]
labels=[]
for img in img_list1:
    im=Image.open(data_path1+'/'+img)
    p=data_path1+'/'+img
    feat=color_feat(im)
    data.append(feat)
    label=p.split(os.path.sep)[-1].split("_")[0]
    labels.append(label)

In [5]:
labels

['Untitled Folder/Dataset/cat',
 'Untitled Folder/Dataset/cat',
 'Untitled Folder/Dataset/cat',
 'Untitled Folder/Dataset/cat',
 'Untitled Folder/Dataset/cat',
 'Untitled Folder/Dataset/cat',
 'Untitled Folder/Dataset/cat',
 'Untitled Folder/Dataset/cat',
 'Untitled Folder/Dataset/cat',
 'Untitled Folder/Dataset/cat',
 'Untitled Folder/Dataset/cat',
 'Untitled Folder/Dataset/cat',
 'Untitled Folder/Dataset/cat',
 'Untitled Folder/Dataset/cat',
 'Untitled Folder/Dataset/cat',
 'Untitled Folder/Dataset/cat',
 'Untitled Folder/Dataset/cow',
 'Untitled Folder/Dataset/cow',
 'Untitled Folder/Dataset/cow',
 'Untitled Folder/Dataset/cow',
 'Untitled Folder/Dataset/cow',
 'Untitled Folder/Dataset/cow',
 'Untitled Folder/Dataset/cow',
 'Untitled Folder/Dataset/cow',
 'Untitled Folder/Dataset/cow',
 'Untitled Folder/Dataset/cow',
 'Untitled Folder/Dataset/cow',
 'Untitled Folder/Dataset/cow',
 'Untitled Folder/Dataset/cow',
 'Untitled Folder/Dataset/cow',
 'Untitled Folder/Dataset/cow',
 'Untitl

In [6]:
le=LabelEncoder()

In [7]:
labels=le.fit_transform(labels)

In [8]:
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2], dtype=int64)

In [9]:
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [10]:
(train_x,test_x,train_y,test_y)=train_test_split(data,labels,test_size=0.25,random_state=1)

In [11]:
from sklearn.naive_bayes import GaussianNB

In [12]:
model=GaussianNB()

In [13]:
model.fit(train_x,train_y)
predictions=model.predict(test_x)
print(metrics.confusion_matrix(test_y,predictions))
print(metrics.classification_report(test_y,predictions))

[[0 2 0]
 [1 4 0]
 [0 3 2]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.44      0.80      0.57         5
           2       1.00      0.40      0.57         5

    accuracy                           0.50        12
   macro avg       0.48      0.40      0.38        12
weighted avg       0.60      0.50      0.48        12



In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
model=LogisticRegression(solver="lbfgs",multi_class="auto")

In [16]:
model.fit(train_x,train_y)
predictions=model.predict(test_x)
print(metrics.confusion_matrix(test_y,predictions))
print(metrics.classification_report(test_y,predictions))

[[2 0 0]
 [2 3 0]
 [0 2 3]]
              precision    recall  f1-score   support

           0       0.50      1.00      0.67         2
           1       0.60      0.60      0.60         5
           2       1.00      0.60      0.75         5

    accuracy                           0.67        12
   macro avg       0.70      0.73      0.67        12
weighted avg       0.75      0.67      0.67        12



C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [17]:
from sklearn.tree import DecisionTreeClassifier

In [18]:
model=DecisionTreeClassifier()

In [19]:
model.fit(train_x,train_y)
predictions=model.predict(test_x)
print(metrics.confusion_matrix(test_y,predictions))
print(metrics.classification_report(test_y,predictions))

[[0 2 0]
 [1 2 2]
 [1 2 2]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.33      0.40      0.36         5
           2       0.50      0.40      0.44         5

    accuracy                           0.33        12
   macro avg       0.28      0.27      0.27        12
weighted avg       0.35      0.33      0.34        12



In [20]:
from sklearn.ensemble import RandomForestClassifier

In [21]:
model=RandomForestClassifier(n_estimators=50)

In [22]:
model.fit(train_x,train_y)
predictions=model.predict(test_x)
print(metrics.confusion_matrix(test_y,predictions))
print(metrics.classification_report(test_y,predictions))

[[0 2 0]
 [1 4 0]
 [1 2 2]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.50      0.80      0.62         5
           2       1.00      0.40      0.57         5

    accuracy                           0.50        12
   macro avg       0.50      0.40      0.40        12
weighted avg       0.62      0.50      0.49        12



In [23]:
from sklearn.neighbors import KNeighborsClassifier

In [24]:
model=KNeighborsClassifier(n_neighbors=1)

In [25]:
model.fit(train_x,train_y)
predictions=model.predict(test_x)
print(metrics.confusion_matrix(test_y,predictions))
print(metrics.classification_report(test_y,predictions))

[[1 1 0]
 [2 3 0]
 [1 1 3]]
              precision    recall  f1-score   support

           0       0.25      0.50      0.33         2
           1       0.60      0.60      0.60         5
           2       1.00      0.60      0.75         5

    accuracy                           0.58        12
   macro avg       0.62      0.57      0.56        12
weighted avg       0.71      0.58      0.62        12



In [26]:
from sklearn.neural_network import MLPClassifier

In [27]:
model=MLPClassifier()

In [28]:
model.fit(train_x,train_y)
predictions=model.predict(test_x)
print(metrics.confusion_matrix(test_y,predictions))
print(metrics.classification_report(test_y,predictions))

[[0 2 0]
 [0 5 0]
 [3 2 0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.56      1.00      0.71         5
           2       0.00      0.00      0.00         5

    accuracy                           0.42        12
   macro avg       0.19      0.33      0.24        12
weighted avg       0.23      0.42      0.30        12



C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
